# **TUGAS NUMPY**

---

Nama    : Rhendy Japelhendal Saragih Sumbayak

NIM     : 235150407111015

Setelah mengikuti workshop Numpy dan Pandas, tentunya kalian sudah mulai memahami hal-hal apa saja yang akan dilakukan oleh Data Scientist dengan Numpy. Sekarang, saatnya mengukur kemampuan kalian dari apa yang telah kalian dapatkan pada workshop sebelumnya.

**Deadline: Jumat, 21 Februari 2025**


# **📊 Numpy Exercise 📊**

Selamat datang di latihan eksplorasi data menggunakan **Numpy**!  

---

## **📌 Soal 1: Regresi Linear** 📝

Saat offline/online assessment kemarin ada persoalaan **Regresi Linear**, nah coba kamu buat menggunakan python dan numpy termasuk poin-poin berikut: <br>
✅ Fungsi regresi mampu menerima array A dan array B dan memprediksi slope dan intercept<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X <br>

In [77]:
import numpy as np

def linear_regression(X, Y):
    # Menghitung jumlah elemen
    n = len(X)
    
    # Menghitung sum dari X, Y, X*Y, dan X^2
    sum_x = np.sum(X)
    sum_y = np.sum(Y)
    sum_xy = np.sum(X * Y)
    sum_x_squared = np.sum(X ** 2)
    
    # Menghitung slope (m)
    m = (n * sum_xy - sum_x * sum_y) / (n * sum_x_squared - sum_x ** 2)
    
    # Menghitung intercept (b)
    b = (sum_y - m * sum_x) / n
    
    return m, b

def predict(X, m, b):
    # Prediksi nilai Y berdasarkan persamaan regresi linear
    return m * X + b

# Contoh data X (input) dan Y (output)
X = np.array([1, 2, 3, 4, 5])  
Y = np.array([2, 4, 5, 4, 5]) 

# Menghitung slope (m) dan intercept (b)
m, b = linear_regression(X, Y)

print(f"Slope (m): {m}")
print(f"Intercept (b): {b}")

# Prediksi nilai Y untuk X baru
new_X = 6
predicted_Y = predict(new_X, m, b)
print(f"Prediksi nilai Y untuk X = {new_X}: {predicted_Y}")

Slope (m): 0.6
Intercept (b): 2.2
Prediksi nilai Y untuk X = 6: 5.8


## **📌 Soal 2: Regresi Polinomial** 📝

Saat offline/online assessment kemarin ada persoalan **Regresi Linear**, nah sekarang coba kamu buat **Regresi Polinomial** menggunakan Python dan NumPy, termasuk poin-poin berikut:<br>
✅ Fungsi regresi mampu menerima array A dan array B serta menyesuaikan data dengan polinomial derajat tertentu.<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X.<br>
✅ Hasil regresi mencetak koefisien polinomial yang dihasilkan.<br>

In [78]:
def polynomial_regression(X, Y, degree):
    # Menyesuaikan data dengan polinomial derajat tertentu
    coefficients = np.polyfit(X, Y, degree)
    return coefficients

def predict_polynomial(X, coefficients):
    # Menggunakan koefisien polinomial untuk memprediksi nilai baru
    polynomial = np.poly1d(coefficients)
    return polynomial(X)

# Contoh data X (input) dan Y (output)
X = np.array([1, 2, 3, 4, 5])  # Fitur input
Y = np.array([2, 8, 18, 32, 50])  # Target output

# Derajat polinomial (misalnya derajat 2 untuk kuadrat)
degree = 2

# Menghitung koefisien polinomial
coefficients = polynomial_regression(X, Y, degree)

# Mencetak koefisien polinomial yang dihasilkan
print(f"Koefisien Polinomial: {coefficients}")

# Prediksi nilai Y untuk X baru
new_X = np.array([6, 7, 8])  # Nilai X baru untuk prediksi
predicted_Y = predict_polynomial(new_X, coefficients)

print(f"Prediksi nilai Y untuk X = {new_X}: {predicted_Y}")


Koefisien Polinomial: [ 2.00000000e+00 -4.92671822e-14  7.62390571e-14]
Prediksi nilai Y untuk X = [6 7 8]: [ 72.  98. 128.]


## **📌 Soal 3: Random Values Array** 📝

Pertama-tama, buatlah **Array Integer 10x10x10** dengan elemen **random** dan carikan:<br>
1️⃣ Cari elemen minimum dan maksimum dalam array tersebut?<br>
2️⃣ Carilah rata-rata dan median seluruh elemen dalam array tersebut?<br>

In [79]:
# Membuat array 10x10x10 dengan elemen random integer antara 0 dan 100
array = np.random.randint(0, 100, size=(10, 10, 10))

# Menampilkan array untuk referensi
print("Array 10x10x10:")
print(array)

# Mencari elemen minimum dan maksimum
min_value = np.min(array)
max_value = np.max(array)

print(f"Elemen minimum dalam array: {min_value}")
print(f"Elemen maksimum dalam array: {max_value}")

Array 10x10x10:
[[[39 56 62 15  6 33 35 92 66 32]
  [33 84 87 51 13 55 21 80 15 66]
  [58 41 11  6 26 24 78 97 97 18]
  [33 11 97 63  5 86 78 24 32 21]
  [34 14  1 77 27 31 72 57 55 59]
  [72 47 20 88 13 92 97 26 98 63]
  [16  4 40 52 22 28  8 25 18 42]
  [64 24 96 89 99 47 35 87 88 65]
  [73 24  0 26 78 18 44  4 69 81]
  [82 55 28 88 81 81 20  3 73 52]]

 [[44 46 23 93 55 23 42 99 34 31]
  [35 64 93  0 26 32 44 55 32 47]
  [76 78 41 31 18 69 73 75 49 48]
  [50 95 21 25 83 15 37 70 68 50]
  [73 49 42 40  8 82 92 80 70 44]
  [35 55  7 78 33 56  6 45 10 47]
  [17 20 96 41 29 38  8 62 55 93]
  [42 37 70 35 50 72 20 75 85 50]
  [17 40 80 42 11 43 50 27 57 72]
  [73 75 69  0 78 82 69 17 42 90]]

 [[96 86 89 73 15  8 39 97 85 26]
  [37 10 45 36 66 92 72 27 61 17]
  [47 67 16 12 44 31 45 25 46 87]
  [68 88 77 40 10 27 85 19 25 79]
  [73 14 38 46 56 31 67 54  1 45]
  [11 17 91 68 67 69 36 95 67 55]
  [65 70  6 76 26 34 12 86 98 74]
  [85 14 70 94  1 82 55 19 61 18]
  [84 35 16  8 17 38 30 32 4

In [80]:
# Mencari rata-rata seluruh elemen dalam array
mean_value = np.mean(array)

# Mencari median seluruh elemen dalam array
median_value = np.median(array)

# Menampilkan hasil
print(f"Rata-rata seluruh elemen dalam array: {mean_value}")
print(f"Median seluruh elemen dalam array: {median_value}")

Rata-rata seluruh elemen dalam array: 49.508
Median seluruh elemen dalam array: 49.0


## **📌 Soal 4: 2D Array Shenanigans** 📝

Tugas kamu disini adalah membuat **Array 2D** sesuai ketentuan masing-masing soal: <br>
1️⃣ Buatlah **array 10x10** yang memiliki angka "5" sebagai bingkai di seluruh tepi luar dan bagian dalam (selain array) berisi "8"? <br>
2️⃣ Buatlah **array 2d 8x8** dengan pola seperti **checkboard/catur** (1 untuk kotak hitam, 0 untuk kotak putih)?<br>
3️⃣ Buatlah **array 2d 15x15** dengan aturan sebagai berikut:
- Jika suatu angka dapat dibagi 2, isi dengan 2.
- Jika suatu angka dapat dibagi 3, isi dengan 3.
- Jika suatu angka dapat dibagi 5, isi dengan 5.
- Jika suatu angka dapat dibagi oleh lebih dari satu kondisi (misal, 6 bisa dibagi 2 & 3), maka simpan gabungan angka tersebut (misal, 6 → "23", 15 → "35").
- Jika tidak memenuhi kondisi apa pun, isi dengan 0.

In [81]:
# Membuat array 10x10 yang berisi angka 8
array_10x10 = np.full((10, 10), 8)

# Menambahkan bingkai angka 5 di tepi luar
array_10x10[0, :] = 5  # Baris pertama
array_10x10[-1, :] = 5  # Baris terakhir
array_10x10[:, 0] = 5   # Kolom pertama
array_10x10[:, -1] = 5  # Kolom terakhir

print("Array 10x10 dengan bingkai 5 dan bagian dalam 8:")
print(array_10x10)

Array 10x10 dengan bingkai 5 dan bagian dalam 8:
[[5 5 5 5 5 5 5 5 5 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 5 5 5 5 5 5 5 5 5]]


In [82]:
# Membuat array 8x8 untuk pola catur
array_8x8 = np.zeros((8, 8), dtype=int)

# Mengisi pola catur
array_8x8[1::2, ::2] = 1  # Kotak hitam pada baris ganjil dan kolom genap
array_8x8[::2, 1::2] = 1  # Kotak hitam pada baris genap dan kolom ganjil

print("\nArray 8x8 dengan pola catur:")
print(array_8x8)


Array 8x8 dengan pola catur:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [83]:
# Membuat array 15x15 dengan aturan pembagian
array_15x15 = np.zeros((15, 15), dtype=object)

# Mengisi array berdasarkan aturan
for i in range(15):
    for j in range(15):
        num = i * 15 + j + 1  # Menghitung angka sesuai posisi dalam array
        result = ''
        
        if num % 2 == 0:
            result += '2'
        if num % 3 == 0:
            result += '3'
        if num % 5 == 0:
            result += '5'
        
        # Jika tidak ada pembagian yang memenuhi, tetap 0
        array_15x15[i, j] = result if result else 0

print("\nArray 15x15 dengan aturan pembagian 2, 3, 5:")
print(array_15x15)


Array 15x15 dengan aturan pembagian 2, 3, 5:
[[0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']]


## **📌 Soal 5: Time & Date** 📝

Kamu disini diminta untuk memanfaatkan fitur numpy untuk tanggal: <br>
1️⃣ Bagaimana dengan numpy, kamu bisa mendapatkan tanggal hari ini, kemarin dan esok hari?<br>
2️⃣ Tampilkan hari yang ada di bulan Mei tahun 2020?<br>

In [84]:
# Mendapatkan tanggal hari ini
today = np.datetime64('today', 'D')

# Mendapatkan tanggal kemarin (1 hari sebelum hari ini)
yesterday = today - np.timedelta64(1, 'D')

# Mendapatkan tanggal esok hari (1 hari setelah hari ini)
tomorrow = today + np.timedelta64(1, 'D')

print(f"Tanggal hari ini: {today}")
print(f"Tanggal kemarin: {yesterday}")
print(f"Tanggal esok hari: {tomorrow}")

Tanggal hari ini: 2025-02-21
Tanggal kemarin: 2025-02-20
Tanggal esok hari: 2025-02-22


In [85]:
# Rentang tanggal dari 1 Mei 2020 hingga 31 Mei 2020
may_dates = np.arange('2020-05-01', '2020-06-01', dtype='datetime64[D]')

# Menampilkan hari dari setiap tanggal
for date in may_dates:
    print(f"Tanggal {date} adalah hari {date.astype('datetime64[D]').item().strftime('%A')}")

Tanggal 2020-05-01 adalah hari Friday
Tanggal 2020-05-02 adalah hari Saturday
Tanggal 2020-05-03 adalah hari Sunday
Tanggal 2020-05-04 adalah hari Monday
Tanggal 2020-05-05 adalah hari Tuesday
Tanggal 2020-05-06 adalah hari Wednesday
Tanggal 2020-05-07 adalah hari Thursday
Tanggal 2020-05-08 adalah hari Friday
Tanggal 2020-05-09 adalah hari Saturday
Tanggal 2020-05-10 adalah hari Sunday
Tanggal 2020-05-11 adalah hari Monday
Tanggal 2020-05-12 adalah hari Tuesday
Tanggal 2020-05-13 adalah hari Wednesday
Tanggal 2020-05-14 adalah hari Thursday
Tanggal 2020-05-15 adalah hari Friday
Tanggal 2020-05-16 adalah hari Saturday
Tanggal 2020-05-17 adalah hari Sunday
Tanggal 2020-05-18 adalah hari Monday
Tanggal 2020-05-19 adalah hari Tuesday
Tanggal 2020-05-20 adalah hari Wednesday
Tanggal 2020-05-21 adalah hari Thursday
Tanggal 2020-05-22 adalah hari Friday
Tanggal 2020-05-23 adalah hari Saturday
Tanggal 2020-05-24 adalah hari Sunday
Tanggal 2020-05-25 adalah hari Monday
Tanggal 2020-05-26 adala

## **📌 Soal 6: Slicing** 📝

Jika diketahui array `A`, maka buatlah program untuk mendapatkan elemen dibawah ini:
```python
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])
```

1️⃣ Ambil elemen yang berada pada baris `ke-4` dan kolom `ke-2` dari array `A` <br>
2️⃣ Buat `array 2D` yang hanya berisi bilangan prima dari `A` <br>
3️⃣ Ambil elemen-elemen yang berada di tepi luar dari array `A` dan gabungkan menjadi `Satu array 1D`. <br>
4️⃣ Dapatkan subbarray berikut:
```python
[[20, 40, 60],
 [80, 100, 120],
 [140, 160, 180],
 [200, 220, 240],
 [260, 280, 300]]
```
5️⃣ Dapatkan subbarray berikut:
```python
 [[30, 40],
 [90, 100],
 [150, 160],
 [210, 220]]
```

In [86]:
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])

# Ambil elemen baris ke-4 dan kolom ke-2
element = A[3, 1]  # Baris ke-4 adalah indeks 3, kolom ke-2 adalah indeks 1
print(f"Elemen pada baris ke-4 dan kolom ke-2: {element}")

Elemen pada baris ke-4 dan kolom ke-2: 200


In [87]:
# Fungsi untuk memeriksa apakah sebuah angka adalah bilangan prima
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Menyaring bilangan prima dari array A
prime_elements = A[np.vectorize(is_prime)(A)]
prime_elements_2d = prime_elements[prime_elements > 0].reshape(-1, 1)  # Membuat array 2D
print(f"Array 2D yang hanya berisi bilangan prima: \n{prime_elements_2d}")

Array 2D yang hanya berisi bilangan prima: 
[]


Tidak ada bilangan prima dari array A

In [88]:
# Mengambil elemen tepi luar dari array A
top = A[0, :]
bottom = A[-1, :]
left = A[:, 0]
right = A[:, -1]

# Menggabungkan elemen-elemen tepi luar menjadi satu array 1D
edge_elements = np.concatenate((top, bottom, left[1:-1], right[1:-1]))  # Menyingkirkan duplikasi sudut
print(f"Elemen tepi luar digabungkan menjadi array 1D: \n{edge_elements}")

Elemen tepi luar digabungkan menjadi array 1D: 
[ 10  20  30  40  50  60 250 260 270 280 290 300  70 130 190 120 180 240]


In [89]:
# Mengambil subarray sesuai permintaan
subarray1 = A[:, [1, 3, 5]]
print(f"Subarray yang diambil: \n{subarray1}")

Subarray yang diambil: 
[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]
 [200 220 240]
 [260 280 300]]


In [90]:
# Mengambil subarray sesuai permintaan
subarray2 = A[:, [2, 3]]
print(f"Subarray yang diambil: \n{subarray2}")

Subarray yang diambil: 
[[ 30  40]
 [ 90 100]
 [150 160]
 [210 220]
 [270 280]]


## **📌 Soal 7: Ekspansi Array** 📝

Jika kamu memiliki array ***Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]***, buatlah kode untuk membuat array R berupa: <br>
***R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]***?

In [91]:
# Array Z yang diberikan
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Membuat array R dengan slicing, dengan setiap subarray terdiri dari 4 elemen berturut-turut
R = np.array([Z[i:i+4] for i in range(len(Z)-3)])

print("Array R:")
print(R)

Array R:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
