<div style="text-align: center;">
    <img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" alt="Numpy Logo" width="500">
    <p style="font-size: 50px; font-weight: bold;">Pengenalan NumPy pada Python</p>
    <p style="font-size: 50px; font-weight: normal;"> Intern BCC 2025</p>
</div>

# Numpy 🧮

**NumPy** atau Numerical Python adalah sebuah library Python yang menyediakan struktur data dan fungsi-fungsi untuk bekerja dengan array dan matriks multidimensi untuk kebutuhan scientific computing menggunakan Python.

**NumPy** meningkatkan efisiensi dalam melakukan operasi dan manipulasi data dengan ukuran yang besar.

In [ ]:
# Kalau kamu menggunakan Google Colab atau Kaggle Notebook, umumnya package numpy sudah pre-installed.
# !pip install numpy

# if you want to install specific version, you can also do this
# !pip install numpy==2.2.3

Fun fact nih,  numpy versi 2.0 keatas struktur internalnya agak berubah dengan versi 1.9 kebawah. Jadi saat awal rilis, ada beberapa package python yang dipakai buat deep learning (misalnya pytorch) itu gak kompatibel atau hanya kompatibel dengan versi numpy tertentu.

ini merupakan kasus conflicted package dependencies di python
- https://stackoverflow.com/questions/74979861/conflicting-package-versions-dependencies-in-python
- https://stackoverflow.com/questions/71689095/how-to-solve-the-pytorch-runtimeerror-numpy-is-not-available-without-upgrading

Untuk menggunakan numpy, kita harus import `numpy` package terlebih dahulu:

In [1]:
import numpy as np # 'np' merupakan alias untuk package numpy paling umum

### Array Numpy

In [10]:
arr1d = np.array([1,2,3]) # array satu dimensi

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]) # array dua dimensi

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                  [[7, 8, 9], [10, 11, 12]]]) # array tiga dimensi


print("Array satu dimensi: \n", arr1d)
print("Array dua dimensi: \n", arr2d)
print("Array tiga dimensi: \n", arr3d)

Array satu dimensi: 
 [1 2 3]
Array dua dimensi: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array tiga dimensi: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Menampilkan informasi tentang array 2D

- `.ndim`: Dimensi suatu array (1D, 2D or etc)
- `.shape`: Ukuran suatu array, keluaran berupa python tuple dan menampilkan axis (dimensi) suatu array.
- `.size`: Jumlah elemen dalam array. Contohnya arr2d memiliki 9 elemen
- `.dtype`: Tipe data yang ada dalam array

In [12]:
print("Dimensi Array 2D:", arr2d.ndim)
print("Ukuran Array 2D:", arr2d.shape)
print("Jumlah elemen Array 2D:", arr2d.size)
print("Tipe Data Array 2D:", arr2d.dtype)

Dimensi Array 2D: 2
Ukuran Array 2D: (3, 3)
Jumlah elemen Array 2D: 9
Tipe Data Array 2D: int64


In [ ]:
### Slicing dan Indexing Array

In [ ]:
print("Element index ke-1 arr1d\t\t:", arr1d[1])
print("Element index ke-1 hingga 2 arr1d\t:", arr1d[1:3])
print("Element baris ke-1 dan kolom ke-2\t:", arr2d[0:2, 0])

In [ ]:
### Menghitung Statistik

In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Menghitung statistik
mean_value = np.mean(arr2d, axis=0)
median_value = np.median(arr2d)
std_deviation = np.std(arr2d)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)

In [ ]:
### Aritmatika


In [ ]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])


# Operasi Transposisi
transposed_arr = arr1.T
transposed_arr = np.transpose(arr1)
print("Transposed Array arr1:\n", transposed_arr)

# Operasi dot product
dot_product = np.dot(arr1, arr2)
dot_product = arr1.dot(arr2)
print("Dot Product:\n", dot_product)


# Operasi penjumlahan
# sum_arr = arr1 + arr2
sum_arr = np.add(arr1, arr2)
print("Penjumlahan:\n", sum_arr)

In [ ]:
### Reshaping Array

In [ ]:
**Reshape** adalah metode dalam NumPy yang digunakan untuk mengubah bentuk (shape/dimensi) dari sebuah array NumPy tanpa mengubah isi datanya.

In [13]:
# Membuat array 1D dengan 9 elemen menggunakan method arrange
# 0, 1, 2, 3, 4, 5, 6, 7, 8

arr1d = np.arange(start=0, step=1, stop=9)
print("Array 1D:")
print(arr1d)

# Mengubah array 1D menjadi matriks 3x3
arr2d_3x3 = arr1d.reshape(3, 3)
print("Matriks 3x3:")
print(arr2d_3x3)

# Mengubah array 1D menjadi vektor baris 1x9
arr2d_row = arr1d.reshape(1, 9)
print("Vektor Baris 1x9:")
print(arr2d_row)

# Mengubah array 1D menjadi vektor kolom 9x1
arr2d_col = arr1d.reshape(9, 1)
print("Vektor Kolom 9x1:")
print(arr2d_col)

Array 1D:
[0 1 2 3 4 5 6 7 8]
Matriks 3x3:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Vektor Baris 1x9:
[[0 1 2 3 4 5 6 7 8]]
Vektor Kolom 9x1:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
